name: 'Clear in Docker'
description: 'Run commands in the latest Clear Linux OS Docker image'
inputs:
  testfunc:
    description: 'Test function to run'
    required: true
    default: 'run_flake8'
runs:
  using: 'docker'
  image: 'Dockerfile'
