name: Autospec Tests

on: [push, pull_request]

jobs:
  test_style:
    runs-on: ubuntu-latest
    name: Flake8
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Run Tests
        uses: ./.github/actions/clearlinux-latest-action
        with:
          testfunc: run_flake8
  test_unit:
    runs-on: ubuntu-latest
    name: Unit
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.0
      - name: Run Tests
        uses: ./.github/actions/clearlinux-latest-action
        with:
          testfunc: run_unittests
